import { CourseExtensionComplementaryActivitiesDataResponse } from "@unidash/api/responses/courseExtensionComplementaryActivitiesDataResponse.interface";

export interface CourseExtensionComplementaryActivitiesDataTableProps {
  courseExtensionComplementaryActivitiesData: CourseExtensionComplementaryActivitiesDataResponse["courseExtensionComplementaryActivitiesData"];
}
