import { CourseSearchComplementaryActivitiesListDataResponse } from "@unidash/api/responses/courseSearchComplementaryActivitiesDataResponse.interface";

export interface CourseSearchComplementaryActivitiesDataTableProps {
  courseSearchComplementaryActivitiesData: CourseSearchComplementaryActivitiesListDataResponse["courseSearchComplementaryActivitiesData"];
}
