import { CourseTeachingComplementaryActivitiesDataResponse } from "@unidash/api/responses/courseTeachingComplementaryActivitiesDataResponse.interface";

export interface CourseTeachingComplementaryActivitiesDataTableProps {
  courseTeachingComplementaryActivitiesData: CourseTeachingComplementaryActivitiesDataResponse["courseTeachingComplementaryActivitiesData"];
}
