import { CourseTeachingComplementaryActivitiesDataResponse } from "@unidash/api/responses/courseTeachingComplementaryActivitiesDataResponse.interface";

export interface EditCourseTeachingComplementaryActivitiesDataFormProps {
  courseTeachingComplementaryActivitiesData: CourseTeachingComplementaryActivitiesDataResponse["courseTeachingComplementaryActivitiesData"];
}
